# docker-compose.yml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - traefik-network
    restart: unless-stopped
  jenkins-blueocean:
    build:
      context: ./jenkins
    user: root
    container_name: jenkins-blueocean
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.gkibria121.com`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      TZ: Asia/Dhaka

    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/gkibria:/var/projects
      - /var/run/docker.sock:/var/run/docker.sock
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - traefik-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pg-admin.gkibria121.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - /mnt/storage/filebrowser/data/files:/srv
      - /mnt/storage/filebrowser.db:/database.db
      - /mnt/storage/filebrowser/filebrowser-config.json:/config.json



    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.gkibria121.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=web"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - traefik-network
  postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - traefik-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USERNAME:-laravel} -d ${POSTGRES_DATABASE:-app}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5 
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.gkibria121.com`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - traefik-network
volumes:
  jenkins-data:
  pgadmin-data:
  postgres-data-production:
networks:
  traefik-network:
    external: true
